image: docker:latest
services:
    - docker:dind

stages:
    - test
    - build
    - containerize
    - deploy

sonarqube-check:
    stage: test
    image: 
      name: sonarsource/sonar-scanner-cli:latest
      entrypoint: [""]
    variables:
      SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
      GIT_DEPTH: "0" 
    cache:
      key: "${CI_JOB_NAME}"
      paths:
       - .sonar/cache
    script: 
      - sonar-scanner
    allow_failure: true
    only:
      - main

build-project:
    image: gradle:latest
    stage: build
    script: 
      - gradle build
    # artifacts:                     
    #   paths:
    #     - 
